# -*- coding: utf-8 -*-
"""Segment Anything Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pzwxUYvRybICzu7pQbdQT6X5I6h4-Iud
"""

!pip install segment-geospatial leafmap localtileserver

import os
import leafmap
import torch
from samgeo import SamGeo, tms_to_geotiff, get_basemaps

m = leafmap.Map(center=[-0.15386345206107715, 34.86414568574279], zoom=12)
m.add_basemap('SATELLITE')
m

if m.user_roi_bounds() is not None:
  bbox = m.user_roi_bounds()
else:
    bbox = [-95.3704, 29.672, -95.368, 29.6775]

image = '/content/LC09_L1TP_169060_20230211_20230211_02_T1_B5.TIF'

tms_to_geotiff(output=image, zoom=20, bbox=bbox, source='Satellite', overwrite=True)

m.add_raster(image, layer_name='Image')
m